- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    personal: "{{ lookup('env', 'HOME') }}/personal"
    use_sudo: "{{ lookup('env', 'USER') != '' }}"
  pre_tasks:
    - name: Update Apt
      become: "{{ use_sudo }}"
      become_method: sudo
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
      - install
      - core
  tasks:
    - name: Include Ssh Setup
      include_tasks: 
        file: tasks/ssh.yml
    - name: Include Zsh Setup
      include_tasks: 
        file: tasks/zsh-setup.yml
    - name: Include Node Setup
      include_tasks: 
        file: tasks/node-setup.yml
    - name: Include Dotfiles Setup
      include_tasks:
        file: tasks/dotfiles.yml
    - name: Include Productivity
      include_tasks:
        file: tasks/productivity.yml
