- name: Install Golang
  become: "{{ use_sudo }}"
  become_method: sudo
  shell: |
    curl -Lo golang.tar.gz "https://go.dev/dl/go1.23.2.linux-amd64.tar.gz"
    rm -rf /usr/local/go
    tar -C /usr/local -xzf golang.tar.gz
  args:
    creates: "{{ ansible_env.HOME }}/golang.tar.gz"
  tags: &tags_for_golang_tasks ["install", "go"]
