- name: Install LazyGit
  become: "{{ use_sudo }}"
  become_method: sudo
  shell: |
    LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*')
    curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
    tar xf lazygit.tar.gz lazygit
    install lazygit /usr/local/bin
  args:
    creates: "/usr/local/bin/lazygit"
  tags:
    - git
    - install
    - productivity

- name: Remove LazyGit tar
  become: "{{ use_sudo }}"
  become_method: sudo
  shell: |
    rm -rf lazygit.tar.gz lazygit
  tags:
    - git
    - install
    - productivity

- name: Install LazyDocker
  shell: curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin/lazydocker"
  tags:
    - install
    - productivity
    - docker

- name: Install neovim
  become: "{{ use_sudo }}"
  become_method: sudo
  shell: |
    curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
    sudo rm -rf /opt/nvim
    sudo tar -C /opt -xzf nvim-linux64.tar.gz
  args:
    creates: "/opt/nvim-linux64"
  tags:
    - install
    - productivity

- name: Remove Neovim tar
  become: "{{ use_sudo }}"
  become_method: sudo
  shell: |
    rm -rf nvim-linux64.tar.gz
  tags:
    - install
    - productivity

- name: Install packages
  become: "{{ use_sudo }}"
  become_method: sudo
  apt: 
    name: ["fzf", "tmux", "ripgrep", "fd-find", "ani-cli", "jq", "httpie"]
  tags:
    - install
    - productivity

- name: Install TMUX Plugin Manager
  shell: |
    git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
    $HOME/.tmux/plugins/tpm/tpm
  args:
    creates: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
  tags:
    - install
    - productivity
