- name: Install ZSH
  become: "{{ use_sudo }}"
  become_method: sudo
  apt: name=zsh
  tags: &tags_for_zsh_tasks [ 'install', 'productivity', 'dotfiles', 'zsh' ]

- name: Change shell to zsh
  become: "{{ use_sudo }}"
  become_method: sudo
  shell: chsh -s $(which zsh)
  tags: *tags_for_zsh_tasks

- name: Oh-My-Zsh
  shell: curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"
  tags: *tags_for_zsh_tasks

- name: Install zsh-autosuggestions
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: '~/.zsh/zsh-autosuggestions'
  tags: *tags_for_zsh_tasks

- name: Install Starship
  become: "{{ use_sudo }}"
  become_method: sudo
  shell: curl -sS https://starship.rs/install.sh | sh -s -- -y
  args:
    creates: "/usr/local/bin/starship"
  tags: *tags_for_zsh_tasks

# - name: Update zshrc
#   replace: 
#     path: $HOME/.zshrc
#     regexp: '^plugins=\('
#     replace: 'plugins=(zsh-autosuggestions '
#   tags: *tags_for_zsh_tasks
